Default: &defaults
  database: Komet.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Komet_test.sqlite3
  <<: *defaults

Staging:
  database: Komet_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Komet_production.sqlite3
  poolsize: 100
  <<: *defaults
